# Generated by Django 5.2.15 on 2026-06-10 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TheiaNgAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Theia NG access',
                'permissions': [('access', 'Can access the Theia NG admin')],
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
