# Generated by Django 5.2.15 on 2026-06-11 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theia_ng', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('position', models.PositiveIntegerField(default=0, help_text='Order in the view selector.')),
                ('model_keys', models.JSONField(blank=True, default=list, verbose_name='Models')),
            ],
            options={
                'verbose_name': 'Menu view',
                'verbose_name_plural': 'Menu views',
                'ordering': ['position', 'name'],
            },
        ),
    ]
