# Generated by Django 5.2.15 on 2026-06-12 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theia_ng', '0002_menuview'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuview',
            name='model_fields',
            field=models.JSONField(blank=True, default=dict, verbose_name='Fields per model'),
        ),
    ]
