# Generated by Django 5.2.15 on 2026-06-27 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theia_ng', '0007_siteconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='button_style',
            field=models.CharField(choices=[('label', 'Label'), ('icon', 'Icon'), ('both', 'Label + icon')], default='label', max_length=8),
        ),
    ]
