# Generated by Django 5.2.15 on 2026-09-08 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theia_ng', '0008_usersettings_button_style'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_key', models.CharField(help_text='app_label.modelname', max_length=100)),
                ('prompt', models.CharField(help_text='What a user would type', max_length=500)),
                ('expected', models.JSONField(help_text='The list state this prompt should produce')),
                ('in_prompt', models.BooleanField(default=False, help_text='Include as a few-shot example in the prompt')),
                ('enabled', models.BooleanField(default=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Assistant example',
                'verbose_name_plural': 'Assistant examples',
                'ordering': ['model_key', 'prompt'],
            },
        ),
        migrations.CreateModel(
            name='AssistHint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('model', 'Model description'), ('field', 'Field explanation'), ('term', 'Dictionary term')], default='field', max_length=10)),
                ('model_key', models.CharField(blank=True, help_text='app_label.modelname — blank applies to all models', max_length=100)),
                ('field_name', models.CharField(blank=True, help_text="For 'field' hints", max_length=100)),
                ('term', models.CharField(blank=True, help_text="For 'term' entries: the word", max_length=100)),
                ('text', models.TextField(help_text='Keep it short and descriptive. Do NOT list trigger words.')),
                ('enabled', models.BooleanField(default=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Assistant hint',
                'verbose_name_plural': 'Assistant hints',
                'ordering': ['model_key', 'kind', 'field_name', 'term'],
            },
        ),
    ]
