# Generated by Django 5.2.15 on 2026-09-29 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theia_ng', '0010_alter_logentry_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='list_columns',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
